//+------------------------------------------------------------------+
//| This MQL is generated by Expert Advisor Builder                  |
//|                http://sufx.core.t3-ism.net/ExpertAdvisorBuilder/ |
//|                                                                  |
//|  In no event will author be liable for any damages whatsoever.   |
//|                      Use at your own risk.                       |
//|                                                                  |
//+------------------- DO NOT REMOVE THIS HEADER --------------------+

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//|                                      PFXT Ichimoku Expert v1.1.mq4  |
//|                         Copyright © 2011, Positive FX Technologies  |
//|  11th June (At damansara hotel)                                     |
//|  Added filter Buy : Buy only when strong bullish crossover          |
//|                     Above Senkou Span A                             |
//|  Added Filter Sell: Sell only with strong bearish crossover         |
//|                     Under Senkou Span B                             |
//|  Valid for all TF with different sets of TP, SL and TS.. cari       |
//|  sendiri larrrr                                                     |
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


#define SIGNAL_NONE 0
#define SIGNAL_BUY   1
#define SIGNAL_SELL  2
#define SIGNAL_CLOSEBUY 3
#define SIGNAL_CLOSESELL 4

#property copyright "Copyright © 2011, Positive FX Technologies"
#property link      "http://positivefxt.blogspot.com"

extern int MagicNumber = 0;
extern bool SignalMail = False;
extern bool EachTickMode = True;
extern double Lots = 1;
extern int Slippage = 3;
extern bool UseStopLoss = True;
extern int StopLoss = 11500;
extern bool UseTakeProfit = True;
extern int TakeProfit = 2000;
extern bool UseTrailingStop = True;
extern int TrailingStop = 545;
extern bool Comments=true;//|--------------------allow comments on chart

int BarCount;
int Current;
bool TickCheck = False;
//+------------------------------------------------------------------+
//| expert initialization function                                   |
//+------------------------------------------------------------------+
int init() {
   BarCount = Bars;

   if (EachTickMode) Current = 0; else Current = 1;

   return(0);
}
//+------------------------------------------------------------------+
//| expert deinitialization function                                 |
//+------------------------------------------------------------------+
int deinit() {
   return(0);
}
//+------------------------------------------------------------------+
//| expert start function                                            |
//+------------------------------------------------------------------+
int start() {
   int Order = SIGNAL_NONE;
   int Total, Ticket;
   double StopLossLevel, TakeProfitLevel;



   if (EachTickMode && Bars != BarCount) TickCheck = False;
   Total = OrdersTotal();
   Order = SIGNAL_NONE;

   //+------------------------------------------------------------------+
   //| Variable Begin                                                   |
   //+------------------------------------------------------------------+


//double Buy1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 1);
//double Buy1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 1);
//double Buy2_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 1);
//double Buy2_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_SENKOUSPANA, Current + 1);

//double Sell1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 1);
//double Sell1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 1);
//double Sell2_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 1);
//double Sell2_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_SENKOUSPANB, Current + 1);

//double CloseBuy1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
//double CloseBuy1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);

//double CloseSell1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
//double CloseSell1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);

//tgh cuba kecilkan cloud, utk lkebih pluang buy sell
//double Buy1_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 1);
//double Buy1_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_KIJUNSEN, Current + 1);
//double Buy2_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 0); // MODE_CHINKOUSPAN   MODE_KIJUNSEN   MODE_SENKOUSPANA
//double Buy2_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_SENKOUSPANA, Current + 0);

//double Sell1_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 1);
//double Sell1_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_KIJUNSEN, Current + 1);
//double Sell2_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 0);
//double Sell2_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_SENKOUSPANB, Current + 0);

//double CloseBuy1_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 1);
//double CloseBuy1_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_KIJUNSEN, Current + 1);
//double CloseBuy2_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 0);
//double CloseBuy2_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_KIJUNSEN, Current + 0);

//double CloseSell1_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 1);
//double CloseSell1_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_KIJUNSEN, Current + 1);
//double CloseSell2_1 = iIchimoku(NULL, 0, 9, 26, 32, MODE_TENKANSEN, Current + 0);
//double CloseSell2_2 = iIchimoku(NULL, 0, 9, 26, 32, MODE_KIJUNSEN, Current + 0);

//CLoud biasa setting 120
//double Buy1_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 1);
//double Buy1_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_KIJUNSEN, Current + 1);
//double Buy2_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 0); // MODE_CHINKOUSPAN   MODE_KIJUNSEN   MODE_SENKOUSPANA
//double Buy2_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_SENKOUSPANA, Current + 0);

//double Sell1_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 1);
//double Sell1_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_KIJUNSEN, Current + 1);
//double Sell2_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 0);
//double Sell2_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_SENKOUSPANB, Current + 0);

//double CloseBuy1_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 1);
//double CloseBuy1_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_KIJUNSEN, Current + 1);
//double CloseBuy2_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 0);
//double CloseBuy2_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_KIJUNSEN, Current + 0);

//double CloseSell1_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 1);
//double CloseSell1_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_KIJUNSEN, Current + 1);
//double CloseSell2_1 = iIchimoku(NULL, 0, 26, 55, 120, MODE_TENKANSEN, Current + 0);
//double CloseSell2_2 = iIchimoku(NULL, 0, 26, 55, 120, MODE_KIJUNSEN, Current + 0);
   
//CLoud biasa setting 52
double Buy1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double Buy1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);
double Buy2_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0); // MODE_CHINKOUSPAN   MODE_KIJUNSEN   MODE_SENKOUSPANA
double Buy2_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_SENKOUSPANA, Current + 0);

double Sell1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double Sell1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);
double Sell2_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double Sell2_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_SENKOUSPANB, Current + 0);

double CloseBuy1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double CloseBuy1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);
double CloseBuy2_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double CloseBuy2_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);

double CloseSell1_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double CloseSell1_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);
double CloseSell2_1 = iIchimoku(NULL, 0, 9, 26, 52, MODE_TENKANSEN, Current + 0);
double CloseSell2_2 = iIchimoku(NULL, 0, 9, 26, 52, MODE_KIJUNSEN, Current + 0);
   
   //+------------------------------------------------------------------+
   //| Variable End                                                     |
   //+------------------------------------------------------------------+

   //Check position
   bool IsTrade = False;

   for (int i = 0; i < Total; i ++) {
      OrderSelect(i, SELECT_BY_POS, MODE_TRADES);
      if(OrderType() <= OP_SELL &&  OrderSymbol() == Symbol()) {
         IsTrade = True;
         if(OrderType() == OP_BUY) {
            //Close

            //+------------------------------------------------------------------+
            //| Signal Begin(Exit Buy)                                           |
            //+------------------------------------------------------------------+

                     if (CloseBuy1_1 < CloseBuy1_2) Order = SIGNAL_CLOSEBUY;


            //+------------------------------------------------------------------+
            //| Signal End(Exit Buy)                                             |
            //+------------------------------------------------------------------+

            if (Order == SIGNAL_CLOSEBUY && ((EachTickMode && !TickCheck) || (!EachTickMode && (Bars != BarCount)))) {
               OrderClose(OrderTicket(), OrderLots(), Bid, Slippage, MediumSeaGreen);
               if (SignalMail) SendMail("[Signal Alert]", "[" + Symbol() + "] " + DoubleToStr(Bid, Digits) + " Close Buy");
               if (!EachTickMode) BarCount = Bars;
               IsTrade = False;
               continue;
            }
            //Trailing stop
            if(UseTrailingStop && TrailingStop > 0) {                 
               if(Bid - OrderOpenPrice() > Point * TrailingStop) {
                  if(OrderStopLoss() < Bid - Point * TrailingStop) {
                     OrderModify(OrderTicket(), OrderOpenPrice(), Bid - Point * TrailingStop, OrderTakeProfit(), 0, MediumSeaGreen);
                     if (!EachTickMode) BarCount = Bars;
                     continue;
                  }
               }
            }
         } else {
            //Close

            //+------------------------------------------------------------------+
            //| Signal Begin(Exit Sell)                                          |
            //+------------------------------------------------------------------+

                     if (CloseSell1_1 > CloseSell1_2) Order = SIGNAL_CLOSESELL;


            //+------------------------------------------------------------------+
            //| Signal End(Exit Sell)                                            |
            //+------------------------------------------------------------------+

            if (Order == SIGNAL_CLOSESELL && ((EachTickMode && !TickCheck) || (!EachTickMode && (Bars != BarCount)))) {
               OrderClose(OrderTicket(), OrderLots(), Ask, Slippage, DarkOrange);
               if (SignalMail) SendMail("[Signal Alert]", "[" + Symbol() + "] " + DoubleToStr(Ask, Digits) + " Close Sell");
               if (!EachTickMode) BarCount = Bars;
               IsTrade = False;
               continue;
            }
            //Trailing stop
            if(UseTrailingStop && TrailingStop > 0) {                 
               if((OrderOpenPrice() - Ask) > (Point * TrailingStop)) {
                  if((OrderStopLoss() > (Ask + Point * TrailingStop)) || (OrderStopLoss() == 0)) {
                     OrderModify(OrderTicket(), OrderOpenPrice(), Ask + Point * TrailingStop, OrderTakeProfit(), 0, DarkOrange);
                     if (!EachTickMode) BarCount = Bars;
                     continue;
                  }
               }
            }
         }
      }
   }

   //+------------------------------------------------------------------+
   //| Signal Begin(Entry)                                              |
   //+------------------------------------------------------------------+

   if (Buy1_1 > Buy1_2 && Buy2_1 > Buy2_2) Order = SIGNAL_BUY;

   if (Sell1_1 < Sell1_2 && Sell2_1 < Sell2_2) Order = SIGNAL_SELL; // Ubah == jadi <, silap waktu compile.. patut taknak sell


   //+------------------------------------------------------------------+
   //| Signal End                                                       |
   //+------------------------------------------------------------------+

   //Buy
   if (Order == SIGNAL_BUY && ((EachTickMode && !TickCheck) || (!EachTickMode && (Bars != BarCount)))) {
      if(!IsTrade) {
         //Check free margin
         if (AccountFreeMargin() < (100 * Lots)) {
            Print("We have no money. Free Margin = ", AccountFreeMargin());
            return(0);
         }

         if (UseStopLoss) StopLossLevel = Ask - StopLoss * Point; else StopLossLevel = 0.0;
         if (UseTakeProfit) TakeProfitLevel = Ask + TakeProfit * Point; else TakeProfitLevel = 0.0;

         Ticket = OrderSend(Symbol(), OP_BUY, Lots, Ask, Slippage, StopLossLevel, TakeProfitLevel, "Buy(#" + MagicNumber + ")", MagicNumber, 0, DodgerBlue);
         if(Ticket > 0) {
            if (OrderSelect(Ticket, SELECT_BY_TICKET, MODE_TRADES)) {
				Print("BUY order opened : ", OrderOpenPrice());
                if (SignalMail) SendMail("[Signal Alert]", "[" + Symbol() + "] " + DoubleToStr(Ask, Digits) + " Open Buy");
			} else {
				Print("Error opening BUY order : ", GetLastError());
			}
         }
         if (EachTickMode) TickCheck = True;
         if (!EachTickMode) BarCount = Bars;
         return(0);
      }
   }

   //Sell
   if (Order == SIGNAL_SELL && ((EachTickMode && !TickCheck) || (!EachTickMode && (Bars != BarCount)))) {
      if(!IsTrade) {
         //Check free margin
         if (AccountFreeMargin() < (1000 * Lots)) {
            Print("We have no money. Free Margin = ", AccountFreeMargin());
            return(0);
         }

         if (UseStopLoss) StopLossLevel = Bid + StopLoss * Point; else StopLossLevel = 0.0;
         if (UseTakeProfit) TakeProfitLevel = Bid - TakeProfit * Point; else TakeProfitLevel = 0.0;

         Ticket = OrderSend(Symbol(), OP_SELL, Lots, Bid, Slippage, StopLossLevel, TakeProfitLevel, "Sell(#" + MagicNumber + ")", MagicNumber, 0, DeepPink);
         if(Ticket > 0) {
            if (OrderSelect(Ticket, SELECT_BY_TICKET, MODE_TRADES)) {
				Print("SELL order opened : ", OrderOpenPrice());
                if (SignalMail) SendMail("[Signal Alert]", "[" + Symbol() + "] " + DoubleToStr(Bid, Digits) + " Open Sell");
			} else {
				Print("Error opening SELL order : ", GetLastError());
			}
         }
         if (EachTickMode) TickCheck = True;
         if (!EachTickMode) BarCount = Bars;
         return(0);
      }
   }

   if (!EachTickMode) BarCount = Bars;
//|---------AMARAN DWIT TARAK.. EKEKEKEKEKE

   int err=0;
   if(Ticket<0)
   {
      if(GetLastError()==134)
      {
         err=1;
         Print("Not enough money!");
      }
      return (-1);
   }
   
   if(Comments)
   {
      Comment("\nCopyright © 2011, Syamrock FX Trading Technologies  mobile: +60103120271 email: radinfx@gmail.com",
              "\n\nL o t s                   =  " + DoubleToStr(Lots,2),
              "\nB a l a n c e         =  " + DoubleToStr(AccountBalance(),2),
              "\nE q u i t y            =  " + DoubleToStr(AccountEquity(),2));
   }


   return(0);
}

//|------------Utk Copyright hasil kerja aku-------------
//+------------------------------------------------------------------+